import { NavItem } from '../interfaces/navbar-link';

//Lien vers le tableau de bord
const TABLEAU_BORD: NavItem = {
  icon: 'pie-chart',
  label: 'Tableau de bord',
  href: '/dashboard',
  open: false,
  active: false,
  show: true,
  subs: [],
  tabs: [],
};

//Lien vers le tableau de bord
const MON_COMPTE: NavItem = {
  label: 'Mon compte',
  icon: 'person',
  href: '/profiles',
  active: false,
  show: true,
  subs: [],
  open: false,
  tabs: [],
};
//Lien des dossiers de validation

// const VALIDATION: NavItem = {
//   label: 'Candidature au permis',
//   icon: 'folder',
//   href: '/validations/dossiers/nouvelles-demandes',
//   active: false,
//   show: false,
//   open: false,
//   subs: [
//     {
//       label: 'Validation',
//       href: '/validations/dossiers/nouvelles-demandes',
//       show: false,
//       active: false,
//       tabs: [
//         {
//           href: '/validations/dossiers/nouvelles-demandes',
//           label: 'Nouvelles demandes',
//           data: 'pending_monitoring_count',
//           active: false,
//           icon: 'person-add',
//           permissions: [
//             'read-dossier-validation',
//             'read-agenda-management',
//             'read-annex-management',
//             'read-permit-categories-management',
//           ],
//           show: false,
//         },
//         {
//           href: '/validations/dossiers/rejetes',
//           label: 'Dossiers rejetés',
//           data: 'rejet_monitoring_count',
//           active: false,
//           icon: 'list',
//           permissions: [
//             'read-dossier-validation',
//             'read-agenda-management',
//             'read-annex-management',
//             'read-permit-categories-management',
//           ],
//           show: false,
//         },
//         {
//           href: '/validations/dossiers/valides',
//           label: ' Dossiers validés',
//           data: 'validate_monitoring_count',
//           active: false,
//           icon: 'list',
//           permissions: [
//             'read-dossier-validation',
//             'read-agenda-management',
//             'read-annex-management',
//             'read-permit-categories-management',
//           ],
//           show: false,
//         },
//       ],
//     },
//     {
//       label: "Justification d'absence",
//       href: '/validations/dossiers/nouvelles-demandes',
//       show: false,
//       active: false,
//       tabs: [
//         {
//           href: '/validations/dossiers/nouvelles-demandes',
//           label: 'Nouvelles demandes',
//           data: 'pending_monitoring_count',
//           active: false,
//           icon: 'person-add',
//           permissions: [
//             'read-dossier-validation',
//             'read-agenda-management',
//             'read-annex-management',
//             'read-permit-categories-management',
//           ],
//           show: false,
//         },
//         {
//           href: '/validations/dossiers/rejetes',
//           label: 'Dossiers rejetés',
//           data: 'rejet_monitoring_count',
//           active: false,
//           icon: 'list',
//           permissions: [
//             'read-dossier-validation',
//             'read-agenda-management',
//             'read-annex-management',
//             'read-permit-categories-management',
//           ],
//           show: false,
//         },
//         {
//           href: '/validations/dossiers/valides',
//           label: ' Dossiers validés',
//           data: 'validate_monitoring_count',
//           active: false,
//           icon: 'list',
//           permissions: [
//             'read-dossier-validation',
//             'read-agenda-management',
//             'read-annex-management',
//             'read-permit-categories-management',
//           ],
//           show: false,
//         },
//       ],
//     },
//   ],
//   tabs: [],
// };
const VALIDATION: NavItem = {
  label: 'Candidature au permis',
  icon: 'folder',
  href: '/validations/dossiers/nouvelles-demandes',
  active: false,
  show: false,
  open: false,
  subs: [],
  tabs: [
    {
      href: '/validations/dossiers/nouvelles-demandes',
      label: 'Nouvelles demandes',
      data: 'pending_monitoring_count',
      active: false,
      icon: 'person-add',
      permissions: [
        'read-dossier-validation',
        'read-agenda-management',
        'read-annex-management',
        'read-permit-categories-management',
      ],
      show: false,
    },
    {
      href: '/validations/dossiers/rejetes',
      label: 'Dossiers rejetés',
      data: 'rejet_monitoring_count',
      active: false,
      icon: 'list',
      permissions: [
        'read-dossier-validation',
        'read-agenda-management',
        'read-annex-management',
        'read-permit-categories-management',
      ],
      show: false,
    },
    {
      href: '/validations/dossiers/valides',
      label: ' Dossiers validés',
      data: 'validate_monitoring_count',
      active: false,
      icon: 'list',
      permissions: [
        'read-dossier-validation',
        'read-agenda-management',
        'read-annex-management',
        'read-permit-categories-management',
      ],
      show: false,
    },
  ],
};

const PARAMETRES: NavItem = {
  label: 'Paramètres',
  icon: 'gear',
  href: '/parametres',
  active: false,
  open: false,
  tabs: [],
  subs: [
    {
      label: 'Paramétrage de base',
      href: '/parametres/base/langues',
      show: false,
      active: false,
      tabs: [
        {
          href: '/parametres/base/langues',
          label: 'Langues',
          data: 'langues_count',
          active: false,
          icon: 'translate',
          permissions: ['read-languages-management'],
          show: false,
        },
        {
          href: '/parametres/base/categorie-permis',
          label: ' Catégorie de permis',
          data: 'category_permis_count',
          active: false,
          icon: 'car-front',
          permissions: ['read-permit-categories-management'],
          show: false,
        },
        {
          href: '/parametres/base/restrictions',
          label: 'Restrictions',
          data: 'restrictions_count',
          active: false,
          icon: 'slash-circle',
          permissions: ['read-restrictions-management'],
          show: false,
        },
        {
          href: '/parametres/base/configuration',
          label: 'Configurations',
          data: '',
          active: false,
          icon: 'gear',
          permissions: ['read-base-configuration', 'read-chapitres-management'],
          show: false,
        },
      ],
    },
    {
      label: "Gestion d'accès",
      href: '/parametres/gestions/administrateurs',
      show: false,
      active: false,
      tabs: [
        {
          href: '/parametres/gestions/administrateurs',
          label: 'Administrateurs',
          data: 'users_count',
          active: false,
          icon: 'people',
          permissions: [
            'read-admin',
            'read-roles',
            'read-titles-management',
            'read-administrative-units-management',
          ],
          show: false,
        },

        {
          href: '/parametres/gestions/roles',
          label: 'Rôles',
          data: 'roles_count',
          active: false,
          icon: 'diagram-3',
          permissions: ['read-roles'],
          show: false,
        },
        {
          href: '/parametres/gestions/titres',
          label: 'Titres',
          data: 'titres_count',
          active: false,
          icon: 'ui-checks',
          permissions: ['read-titles-management'],
          show: false,
        },

        {
          href: '/parametres/gestions/unite-admins',
          label: 'Unité administrative',
          data: 'uniteadmins_count',
          active: false,
          icon: 'houses',
          permissions: ['read-administrative-units-management'],
          show: false,
        },
      ],
    },
    {
      label: 'Signatures',
      href: '/parametres/signatures/signataires',
      show: false,
      active: false,
      tabs: [
        {
          href: '/parametres/signatures/signataires',
          label: 'Signataires',
          data: 'signataires_count',
          active: false,
          icon: 'person-lines-fill',
          permissions: ['read-signatures'],
          show: false,
        },
        {
          href: '/parametres/signatures/acte-signes',
          label: ' Acte Signés',
          data: 'acte_signes_count',
          active: false,
          icon: 'file-earmark-check',
          permissions: ['read-signatures'],
          show: false,
        },
      ],
    },
    {
      label: 'Unités territoriales',
      href: '/parametres/territoriales',
      show: false,
      active: false,
      tabs: [
        {
          href: '/parametres/territoriales',
          label: ' Annexes ANaTT',
          data: 'annexes_count',
          active: false,
          icon: 'buildings',
          permissions: ['read-annex-management'],
          show: false,
        },
        {
          href: '/parametres/territoriales/departements',
          label: 'Départements',
          data: 'departements_count',
          active: false,
          icon: 'menu-button',
          permissions: ['read-department'],
          show: false,
        },
        {
          href: '/parametres/territoriales/communes',
          label: 'Communes',
          data: 'communes_count',
          active: false,
          icon: 'file-earmark-check"',
          permissions: ['read-commune'],
          show: false,
        },

        {
          href: '/parametres/territoriales/arrondissements',
          label: 'Arrondissements',
          data: 'arondissements_count',
          active: false,
          icon: 'map"',
          permissions: ['read-arrondissement'],
          show: false,
        },
      ],
    },
    {
      label: 'Gestions QCM',
      href: '/parametres/examatique/questions',
      show: false,
      active: false,
      tabs: [
        {
          href: '/parametres/examatique/questions',
          label: 'Questions',
          data: 'questions_count',
          active: false,
          icon: 'question-circle',
          permissions: ['read-qestion-management', 'read-languages-management'],
          show: false,
        },
        {
          href: '/parametres/examatique/reponses',
          label: 'Réponses possibles',
          data: 'reponses_count',
          active: false,
          icon: 'reply',
          permissions: ['read-reponses-possible-management'],
          show: false,
        },
        {
          href: '/parametres/examatique/bareme-conduites',
          label: 'Barème conduite',
          data: 'baremes_count',
          active: false,
          icon: 'file-text',
          permissions: [
            'read-baremes-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
        {
          href: '/parametres/examatique/chapitres',
          label: 'Chapitres',
          data: 'chapitres_count',
          active: false,
          icon: 'list-ol',
          permissions: [
            'read-chapitres-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
      ],
    },

    {
      label: 'Gestion des compositions',
      active: false,
      href: '/parametres/inspections/inspecteurs',
      show: false,
      tabs: [
        {
          href: '/parametres/inspections/inspecteurs',
          label: 'Superviseur de salle',
          data: 'inspecteurs_count',
          active: false,
          icon: 'person-lines-fill',
          permissions: [
            'read-inspections',
            'read-admin',
            'read-annex-management',
            'read-agenda-management',
          ],
          show: false,
        },
        {
          href: '/parametres/inspections/examinateurs',
          label: 'Examinateurs',
          data: 'examinateurs_count',
          active: false,
          icon: 'file-earmark-check',
          permissions: [
            'read-inspections',
            'read-admin',
            'read-annex-management',
            'read-agenda-management',
          ],
          show: false,
        },
      ],
    },
  ],
  show: false,
};

const RESULTATS: NavItem = {
  label: "Résultats d'examens",
  icon: 'flag',
  href: '/resultats/deliberations/admis',
  active: false,
  show: false,
  tabs: [
    {
      href: '/resultats/deliberations/admis',
      label: 'Les admis',
      icon: 'list-check',
      data: 'admis_count',
      active: false,
      permissions: [
        'read-exam-results-management',
        'read-agenda-management',
        'read-annex-management',
        'read-permit-categories-management',
      ],
      show: false,
    },
  ],
  open: false,
  subs: [
    // {
    //   href: '/resultats/admis-definitifs',
    //   label: 'Admis définitifs',
    //   active: false,
    //   show: false,
    //   tabs: [
    //     {
    //       href: '/resultats/admis-definitifs',
    //       label: 'Admis définitifs',
    //       icon: 'command',
    //       data: '',
    //       active: false,
    //       permissions: ['examen-resultat', 'all'],
    //       show: false,
    //     },
    //   ],
    // },
  ],
};

const TRANSMISSIONS: NavItem = {
  label: 'Transmissions',
  icon: 'command',
  href: '/resultats/admis-definitifs',
  active: false,
  show: false,
  tabs: [
    {
      href: '/resultats/admis-definitifs',
      label: 'Admis définitifs',
      icon: 'command',
      data: '',
      active: false,
      permissions: [
        'read-transmission-menu-access',
        'read-permit-categories-management',
        'read-agenda-management',
        'read-annex-management',
      ],
      show: false,
    },
  ],
  open: false,
  subs: [],
};
const PROGRAMMATION: NavItem = {
  label: 'Programmation',
  icon: 'calendar4-week',
  href: '/programmations/codes',
  active: false,
  show: false,
  subs: [],
  tabs: [
    {
      href: '/programmations/codes',
      label: 'Programmation du code',
      icon: 'sign-no-left-turn',
      data: 'resultat_conduites_count',
      active: false,
      permissions: [
        'read-programming',
        'read-agenda-management',
        'read-annex-management',
      ],
      show: false,
    },
    {
      href: '/programmations/conduites',
      label: 'Programmation de conduite',
      icon: 'taxi-front',
      data: 'resultat_codes_count',
      active: false,
      permissions: [
        'read-programming',
        'read-agenda-management',
        'read-annex-management',
      ],
      show: false,
    },
  ],
  open: false,
};

const AUTO_ECOLES: NavItem = {
  label: 'Auto-Ecoles',
  icon: 'recycle',
  href: '/auto-ecoles',
  active: false,
  tabs: [],
  show: false,
  subs: [
    {
      label: 'Gestion des auto-écoles',
      href: '/auto-ecoles/listes/all',
      active: false,
      tabs: [
        {
          href: '/auto-ecoles/listes/all',
          label: 'Auto-écoles',
          icon: 'recycle',
          data: 'auto_ecoles_count',
          active: false,
          permissions: ['read-driving-school-management'],
          show: false,
        },
        {
          href: '/auto-ecoles/listes/actives',
          label: 'Licences actives',
          icon: 'list',
          data: 'licences_actives_count',
          active: false,
          permissions: ['read-driving-school-management'],
          show: false,
        },
        {
          href: '/auto-ecoles/listes/expires',
          label: 'Licences expirées',
          icon: 'list',
          data: 'licences_expirees_count',
          active: false,
          permissions: ['read-driving-school-management'],
          show: false,
        },
      ],
      show: false,
    },
    {
      label: 'Validation des agréments',
      href: '/auto-ecoles/agreements/news',
      active: false,
      tabs: [
        {
          href: '/auto-ecoles/agreements/news',
          label: 'Nouveaux agréments',
          icon: 'explicit',
          data: 'agrement_news_count',
          active: false,
          permissions: ['read-agreement-management'],
          show: false,
        },
        {
          href: '/auto-ecoles/agreements/rejets',
          label: 'Agréements rejetés',
          icon: 'list',
          data: 'agrement_rejets_count',
          active: false,
          permissions: ['read-agreement-management'],
          show: false,
        },
        {
          href: '/auto-ecoles/agreements/valides',
          label: 'Agréements validés',
          icon: 'list-check',
          data: 'agrement_valides_count',
          active: false,
          permissions: ['read-agreement-management'],
          show: false,
        },
      ],
      show: false,
    },
    {
      label: 'Validation des licences',
      href: '/auto-ecoles/demande-licence/nouvelles-licences',
      active: false,
      tabs: [
        {
          href: '/auto-ecoles/demande-licence/nouvelles-licences',
          label: 'Nouvelles licences',
          icon: 'explicit',
          data: 'demande_licence_news_count',
          active: false,
          permissions: ['read-licences-management'],
          show: false,
        },
        {
          href: '/auto-ecoles/demande-licence/licences-rejetees',
          label: 'Licences rejetées',
          icon: 'list',
          data: 'demande_licence_rejets_count',
          active: false,
          permissions: ['read-licences-management'],
          show: false,
        },
        {
          href: '/auto-ecoles/demande-licence/licences-validees',
          label: 'Licences validées',
          icon: 'list-check',
          data: 'demande_licence_valides_count',
          active: false,
          permissions: ['read-licences-management'],
          show: false,
        },
      ],
      show: false,
    },
  ],
  open: false,
};

const AGENDA: NavItem = {
  label: 'Agenda',
  icon: 'calendar3',
  href: '/agendas/session-examens',
  active: false,
  show: false,
  subs: [],
  tabs: [
    {
      href: '/agendas/session-examens',
      label: "Sessions d'examen",
      icon: 'calendar3',
      data: 'resultat_conduites_count',
      active: false,
      permissions: ['read-agenda-management'],
      show: false,
    },
    {
      href: '/agendas/editer-calendrier',
      label: ' Editer le calendrier',
      icon: 'calendar3-event',
      data: 'resultat_codes_count',
      active: false,
      permissions: ['read-agenda-management'],
      show: false,
    },
  ],
  open: false,
};
const CANDIDATS: NavItem = {
  label: 'Candidats',
  icon: 'people',
  href: '/candidats',
  active: false,
  show: false,
  subs: [],
  tabs: [
    {
      href: '/candidats',
      label: 'Candidats',
      icon: 'people',
      data: 'candidats_count',
      active: false,
      permissions: ['read-candidates-menu-access'],
      show: false,
    },
    {
      href: '/candidats/editions',
      label: 'Laisser passer',
      icon: 'people',
      data: '',
      active: false,
      permissions: ['read-candidates-menu-access'],
      show: false,
    },
  ],
  open: false,
};

const REPORTING: NavItem = {
  label: 'Reporting',
  icon: 'cash-stack',
  href: '/reporting/paiements',
  active: false,
  show: false,
  subs: [],
  tabs: [
    {
      href: '/reporting/paiements',
      label: "Paiements pour l'examen du permis de conduire",
      icon: 'file-earmark-text',
      data: 'resultat_conduites_count',
      active: false,
      permissions: ['read-reporting-management', 'read-agenda-management'],
      show: false,
    },
    {
      href: '/reporting/paiement-titres-derives',
      label: 'Paiements pour les titres dévirés',
      icon: 'file-earmark-ruled',
      data: 'resultat_conduitesf_count',
      active: false,
      permissions: ['read-reporting-management', 'read-agenda-management'],
      show: false,
    },
  ],
  open: false,
};

const E_SERVICES: NavItem = {
  label: 'Titres dérivés',
  icon: 'list-check',
  href: '/services',
  active: false,
  show: false,
  tabs: [],
  subs: [
    {
      label: 'Authenticité du permis',
      href: '/services/authenticite-permis',
      active: false,
      tabs: [
        {
          href: '/services/authenticite-permis/nouvelles',
          label: 'Nouvelles demandes',
          icon: 'patch-question',
          data: 'authenticite_init_count',
          active: false,
          permissions: ['read-permit-authentication'],
          show: false,
        },
        {
          href: '/services/authenticite-permis/rejets',
          label: 'Demandes rejetées',
          icon: 'patch-exclamation',
          data: 'authenticite_rejets_count',
          active: false,
          permissions: ['read-permit-authentication'],
          show: false,
        },
        {
          href: '/services/authenticite-permis/valides',
          label: 'Demandes validées',
          icon: 'patch-check-fill',
          data: 'authenticite_validate_count',
          active: false,
          permissions: ['read-permit-authentication'],
          show: false,
        },
      ],
      show: false,
    },
    {
      label: 'Remplacement ou duplicata du permis',
      href: '/services/duplicata-remplacement-permis',
      active: false,
      tabs: [
        {
          href: '/services/duplicata-remplacement-permis/nouvelles',
          label: 'Nouvelles demandes',
          icon: 'file-earmark-text',
          data: 'duplicata_init_count',
          active: false,
          permissions: ['read-permit-replacement-duplicate'],
          show: false,
        },

        {
          href: '/services/duplicata-remplacement-permis/rejetes',
          label: 'Demandes rejetées',
          icon: 'file-earmark-x',
          data: 'duplicata_rejet_count',
          active: false,
          permissions: ['read-permit-replacement-duplicate'],
          show: false,
        },
        {
          href: '/services/duplicata-remplacement-permis/valides',
          label: 'Demandes validées',
          icon: 'file-earmark-check',
          data: 'duplicata_validate_count',
          active: false,
          permissions: ['read-permit-replacement-duplicate'],
          show: false,
        },
      ],

      show: false,
    },
    {
      label: 'Permis international',
      href: '/services/permis-international/nouvelles',
      active: false,
      tabs: [
        {
          href: '/services/permis-international/nouvelles',
          label: 'Nouvelles demandes',
          icon: 'patch-question',
          data: 'permis_inter_init_count',
          active: false,
          permissions: ['read-international-permit'],
          show: false,
        },
        {
          href: '/services/permis-international/rejets',
          label: 'Demandes rejetées',
          icon: 'patch-exclamation',
          data: 'permis_inter_rejets_count',
          active: false,
          permissions: ['read-international-permit'],
          show: false,
        },
        {
          href: '/services/permis-international/valides',
          label: 'Demandes validées',
          icon: 'patch-check-fill',
          data: 'permis_inter_valide_count',
          active: false,
          permissions: ['read-international-permit'],
          show: false,
        },
      ],
      show: false,
    },
    {
      label: 'Echange de permis',
      href: '/services/echange-permis/nouvelles',
      active: false,
      tabs: [
        {
          href: '/services/echange-permis/nouvelles',
          label: 'Nouvelles demandes',
          icon: 'patch-question',
          data: 'echange_permis_init_count',
          active: false,
          permissions: ['read-permit-exchange'],
          show: false,
        },
        {
          href: '/services/echange-permis/rejets',
          label: 'Demandes rejetées',
          icon: 'patch-exclamation',
          data: 'echange_permis_rejets_count',
          active: false,
          permissions: ['read-permit-exchange'],
          show: false,
        },
        {
          href: '/services/echange-permis/valides',
          label: 'Demandes validées',
          icon: 'patch-check-fill',
          data: 'echange_permis_valide_count',
          active: false,
          permissions: ['read-permit-exchange'],
          show: false,
        },
      ],
      show: false,
    },
    {
      label: 'Prorogation de permis',
      href: '/services/prorogation-permis/nouvelles',
      active: false,
      tabs: [
        {
          href: '/services/prorogation-permis/nouvelles',
          label: 'Nouvelles demandes',
          icon: 'patch-question',
          data: 'prorogation_init_count',
          active: false,
          permissions: ['read-permit-extension'],
          show: false,
        },
        {
          href: '/services/prorogation-permis/rejets',
          label: 'Demandes rejetées',
          icon: 'patch-exclamation',
          data: 'prorogation_rejets_count',
          active: false,
          permissions: ['read-permit-extension'],
          show: false,
        },
        {
          href: '/services/prorogation-permis/valides',
          label: 'Demandes validées',
          icon: 'patch-check-fill',
          data: 'prorogation_valide_count',
          active: false,
          permissions: ['read-permit-extension'],
          show: false,
        },
      ],
      show: false,
    },
  ],
  open: false,
};

const STATISTIQUES: NavItem = {
  label: 'Statistiques',
  icon: 'bar-chart-line',
  href: '/statistiques/rapports',
  active: false,
  show: false,
  subs: [],
  tabs: [
    {
      href: '/statistiques/rapports',
      label: 'Rapports',
      icon: 'file-earmark-text',
      data: 'resultat_conduites_count',
      active: false,
      permissions: [
        'read-statistics',
        'read-agenda-management',
        'read-annex-management',
      ],
      show: false,
    },
    {
      href: '/statistiques/systemes-de-filtrage',
      label: 'Graphes',
      icon: 'bar-chart-line',
      data: 'resultat_conduites_count',
      active: false,
      permissions: [
        'read-statistics',
        'read-agenda-management',
        'read-annex-management',
        'read-languages-management',
        'read-permit-categories-management',
      ],
      show: false,
    },
  ],
  open: false,
};

const RECRUTEMENT: NavItem = {
  label: 'Professionnels',
  icon: 'list-check',
  href: '/recrutements',
  active: false,
  tabs: [],
  show: false,
  subs: [
    {
      label: 'Enrôlement des examinateurs',
      href: '/recrutements/examinateurs/nouvelles',
      active: false,
      tabs: [
        {
          href: '/recrutements/examinateurs/nouvelles',
          label: 'Nouvelles demandes',
          icon: 'patch-question',
          data: 'r_examinateurs_init_count',
          active: false,
          permissions: [
            'read-examiner-recruitment',
            'read-administrative-units-management',
            'read-titles-management',
            'read-roles',
          ],
          show: false,
        },
        {
          href: '/recrutements/examinateurs/rejets',
          label: 'Demandes rejetées',
          icon: 'patch-exclamation',
          data: 'r_examinateurs_rejets_count',
          active: false,
          permissions: [
            'read-examiner-recruitment',
            'read-administrative-units-management',
            'read-titles-management',
            'read-roles',
          ],
          show: false,
        },
        {
          href: '/recrutements/examinateurs/valides',
          label: 'Demandes validées',
          icon: 'patch-check-fill',
          data: 'r_examinateurs_validate_count',
          active: false,
          permissions: [
            'read-examiner-recruitment',
            'read-administrative-units-management',
            'read-titles-management',
            'read-roles',
          ],
          show: false,
        },
      ],
      show: false,
    },
    {
      label: 'Validation dossier (moniteurs)',
      href: '/recrutements/moniteurs/nouvelles',
      active: false,
      tabs: [
        {
          href: '/recrutements/moniteurs/nouvelles',
          label: 'Nouvelles demandes',
          icon: 'patch-question',
          data: 'r_moniteurs_init_count',
          active: false,
          permissions: ['read-monitor-recruitment'],
          show: false,
        },
        {
          href: '/recrutements/moniteurs/rejets',
          label: 'Demandes rejetées',
          icon: 'patch-exclamation',
          data: 'r_moniteurs_rejets_count',
          active: false,
          permissions: ['read-monitor-recruitment'],
          show: false,
        },
        {
          href: '/recrutements/moniteurs/valides',
          label: 'Demandes validées',
          icon: 'patch-check-fill',
          data: 'r_moniteurs_validate_count',
          active: false,
          permissions: ['read-monitor-recruitment'],
          show: false,
        },
      ],
      show: false,
    },
    {
      label: 'Gestion des recruteurs',
      href: '/recrutements/conducteurs',
      active: false,
      tabs: [
        {
          href: '/recrutements/conducteurs/entreprises',
          label: 'Entreprises',
          icon: 'car',
          data: 'r_entreprises_count',
          active: false,
          permissions: [
            'read-company-recruitment-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
      ],

      show: false,
    },

    {
      label: 'Validation Dossier (conducteurs)',
      href: '/recrutements/gestion-recrutement/nouvelles',
      active: false,
      tabs: [
        {
          href: '/recrutements/gestion-recrutement/nouvelles',
          label: 'Nouvelle demande',
          icon: 'car',
          data: 'r_gestion_pending_count',
          active: false,
          permissions: [
            'read-company-recruitment-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
        {
          href: '/recrutements/gestion-recrutement/rejets',
          label: 'Demandes rejetées',
          icon: 'car',
          data: 'r_gestion_rejet_count',
          active: false,
          permissions: [
            'read-company-recruitment-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
        {
          href: '/recrutements/gestion-recrutement/valides',
          label: 'Demandes validées',
          icon: 'car',
          data: 'r_gestion_validate_count',
          active: false,
          permissions: [
            'read-company-recruitment-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
      ],

      show: false,
    },

    {
      label: 'Programmation test recrutement',
      href: '/recrutements/programmation/codes',
      active: false,
      tabs: [
        {
          href: '/recrutements/programmation/codes',
          label: 'Programmation du code',
          icon: 'sign-no-left-turn',
          data: 'resultat_conduites_count',
          active: false,
          permissions: [
            'read-company-recruitment-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
        {
          href: '/recrutements/programmation/conduites',
          label: 'Programmation de conduite',
          icon: 'taxi-front',
          data: 'resultat_codes_count',
          active: false,
          permissions: [
            'read-company-recruitment-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
      ],
      show: false,
    },
    {
      label: 'Résultats (test recrutement)',
      href: '/recrutements/resultat',
      active: false,
      tabs: [
        {
          href: '/recrutements/resultat',
          label: 'Résultats',
          icon: 'car',
          data: 'r_entreprises_count',
          active: false,
          permissions: [
            'read-company-recruitment-management',
            'read-permit-categories-management',
          ],
          show: false,
        },
      ],

      show: false,
    },
  ],
  open: false,
};

const FAQ: NavItem = {
  label: 'FAQ',
  icon: 'question-circle',
  href: '/faqs',
  active: false,
  show: false,
  subs: [],
  tabs: [
    {
      label: 'FAQs',
      icon: 'list',
      href: 'faqs',
      active: false,
      show: false,
      data: '',
      permissions: ['read-faq-management'],
    },
  ],
  open: false,
};
const DISPENSE_PAYMENTS: NavItem = {
  label: 'Dispenses de paiement',
  icon: 'cash',
  href: '/dispenses-payments',
  active: false,
  show: false,
  subs: [],
  tabs: [
    {
      href: '/dispenses-payments',
      label: 'Dispenses de paiement',
      icon: 'cash',
      data: '',
      active: false,
      permissions: ['read-dispense-paiement'],
      show: false,
    },
  ],
  open: false,
};
const LOGS: NavItem = {
  label: 'LOGS',
  icon: 'list',
  href: '/logs',
  active: false,
  show: false,
  subs: [],
  tabs: [
    {
      label: 'LOGS',
      icon: 'list',
      href: '/logs',
      active: false,
      show: false,
      data: '',
      permissions: ['read-log'],
    },
  ],
  open: false,
};
export const ROUTES: NavItem[] = [
  TABLEAU_BORD,
  MON_COMPTE,
  PARAMETRES,
  VALIDATION,
  PROGRAMMATION,
  REPORTING,
  AGENDA,
  CANDIDATS,
  AUTO_ECOLES,
  E_SERVICES,
  RECRUTEMENT,
  RESULTATS,
  TRANSMISSIONS,
  STATISTIQUES,
  DISPENSE_PAYMENTS,
  FAQ,
  LOGS,
];
